import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname,join,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(fileURLToPath(new URL('../dist',import.meta.url)));
const port=Number(process.env.PORT??4173);
const base=process.env.BASE_PATH??'/';
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.webp':'image/webp','.xml':'application/xml','.txt':'text/plain; charset=utf-8'};
const server=createServer(async(req,res)=>{try{if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);res.end();return;}const url=new URL(req.url,'http://localhost');const path=decodeURIComponent(url.pathname);if(!path.startsWith(base)){res.writeHead(404);res.end('Not found');return;}let file=resolve(root,path.slice(base.length));if(file!==root&&!file.startsWith(root+sep)){res.writeHead(403);res.end('Forbidden');return;}let info;try{info=await stat(file);}catch{}if(info?.isDirectory()){if(!path.endsWith('/')){res.writeHead(308,{Location:path+'/'+url.search});res.end();return;}file=join(file,'index.html');}let body;let status=200;try{body=await readFile(file);}catch{status=404;file=join(root,'404.html');body=await readFile(file);}res.writeHead(status,{'Content-Type':types[extname(file)]??'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(req.method==='HEAD'?undefined:body);}catch{res.writeHead(400);res.end('Bad request');}});
server.listen(port,'127.0.0.1',()=>console.log(`Preview: http://localhost:${port}${base}`));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>process.exit(0)));
