const $=id=>document.getElementById(id);let items=[];let selected=null;let offset=0;let requestVersion=0;
const status=$('admin-status');
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await response.json();if(!response.ok){if(response.status===401){$('inbox-panel').hidden=true;$('login-panel').hidden=false;$('inquiry-dialog').close();}throw new Error(data.error??'Request failed.');}return data;}
function node(tag,text,className){const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;return el;}
async function load(){const version=++requestVersion;status.textContent='Loading inquiries…';try{const data=await api('/api/admin/inquiries?'+new URLSearchParams({q:$('query').value,status:$('status-filter').value,offset:String(offset)}));if(version!==requestVersion)return;items=data.items;$('inbox-list').replaceChildren();if(!items.length)$('inbox-list').append(node('p','No inquiries match this view.','empty-inbox'));for(const item of items){const row=node('button','','inquiry-row');row.type='button';const main=node('span','','inquiry-main');main.append(node('strong',item.name),node('span',item.company||item.email));row.append(main,node('span',item.service,'inquiry-service'),node('span',item.status,'status '+item.status),node('time',new Date(item.created_at).toLocaleDateString()));row.addEventListener('click',()=>show(item));$('inbox-list').append(row);}$('previous').disabled=offset===0;$('next').disabled=!data.hasMore;$('page-number').textContent='Page '+(offset/50+1);status.textContent=items.length+' inquiries shown.';}catch(error){status.textContent=error.message;}}
function show(item){selected=item;$('detail-title').textContent=item.name;$('detail-message').textContent=item.message;$('detail-status').value=item.status;$('detail-feedback').textContent='';$('detail-facts').replaceChildren();for(const[label,value]of [['Email',item.email],['Company',item.company||'Not provided'],['Service',item.service],['Budget',item.budget],['Timing',item.timeline],['Reference',item.id.slice(0,8).toUpperCase()]]){const row=node('div','');row.append(node('dt',label),node('dd',value));$('detail-facts').append(row);}$('reply').href='mailto:'+encodeURIComponent(item.email)+'?subject='+encodeURIComponent('Your Maxel project inquiry — '+item.id.slice(0,8).toUpperCase());$('inquiry-dialog').showModal();}
$('login-form').addEventListener('submit',async event=>{event.preventDefault();$('login-button').disabled=true;status.textContent='Signing in…';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('admin-password').value})});$('admin-password').value='';$('login-panel').hidden=true;$('inbox-panel').hidden=false;await load();}catch(error){status.textContent=error.message;}finally{$('login-button').disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST',body:'{}'});items=[];$('inbox-list').replaceChildren();$('inbox-panel').hidden=true;$('login-panel').hidden=false;status.textContent='Signed out.';}catch(error){status.textContent=error.message;}});
$('search-form').addEventListener('submit',event=>{event.preventDefault();offset=0;load();});$('status-filter').addEventListener('change',()=>{offset=0;load();});$('next').addEventListener('click',()=>{offset+=50;load();});$('previous').addEventListener('click',()=>{offset=Math.max(0,offset-50);load();});$('close-detail').addEventListener('click',()=>$('inquiry-dialog').close());
$('save-status').addEventListener('click',async()=>{if(!selected)return;$('save-status').disabled=true;try{await api('/api/admin/inquiries/'+selected.id,{method:'PATCH',body:JSON.stringify({status:$('detail-status').value})});$('detail-feedback').textContent='Status saved.';await load();}catch(error){$('detail-feedback').textContent=error.message;}finally{$('save-status').disabled=false;}});
$('login-button').disabled=false;
api('/api/admin/session').then(data=>{if(data.authenticated){$('login-panel').hidden=true;$('inbox-panel').hidden=false;load();}}).catch(error=>status.textContent=error.message);
